owner: thzjy
repo: upptime

sites:
  - name: New API Health
    url: https://logox.top/health

status-website:
  baseUrl: /upptime

  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: New API Status

  introTitle: "**New API** 状态页"
  introMessage: 这是 new-api 的外部可用性监控页面。

  navbar:
    - title: Status
      href: /

    - title: GitHub
      href: https://github.com/thzjy/upptime
