#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

branch="${1:-master}"

if [ -d ".git/rebase-merge" ] || [ -d ".git/rebase-apply" ]; then
  echo "A rebase is already in progress. Resolve or abort it before running this script." >&2
  exit 1
fi

mkdir -p .github/workflows
cp probe_dashboard/github/workflows/probe-dashboard.yml .github/workflows/probe-dashboard.yml

rm -rf probe_dashboard/scripts/__pycache__

# These files are generated by the scheduled workflow and change frequently.
# Do not include local generated copies in manual layout/script commits.
for generated in \
  probe_dashboard/pages/data/probe-dashboard.json \
  probe_dashboard/pages/data/probe-history.json \
  probe_dashboard/pages/index.html
do
  if git ls-files --error-unmatch "$generated" >/dev/null 2>&1; then
    git restore -- "$generated"
  fi
done

git pull --rebase --autostash origin "$branch"

git add \
  .github/workflows/probe-dashboard.yml \
  probe_dashboard/.gitignore \
  probe_dashboard/github/workflows/probe-dashboard.yml \
  probe_dashboard/scripts/probe_dashboard.py \
  probe_dashboard/scripts/push_probe_dashboard.sh \
  probe_dashboard/pages/logo.svg

if git diff --cached --quiet; then
  echo "No probe dashboard source changes to commit."
else
  git commit -m "Update probe dashboard"
fi

git push origin "$branch"
